[package]
name = "type_hash_core"
version = "0.2.0"
authors = ["Peter Hall <peterjoel@gmail.com"]
edition = "2018"
license = "MIT"
description = """
Internal types for the type_hash crate.
"""

[dependencies]
fnv = "1.0.7"
