[package]
name = "type_hash"
version = "0.1.0"
authors = ["Peter Hall <peterjoel@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
type_hash_core = { path = "../core" }
type_hash_macros = { path = "../macros" }
